// Code generated by ifacemaker; DO NOT EDIT.

package realty

import (
	"realty/internal/domain"
)

// Controller describes methods, implemented by the repository package.
type Repository interface {
	CreateHouse(house *domain.House) (*domain.House, error)
	GetHouseByID(id int64) (*domain.House, error)
	CreateFlat(flat *domain.Flat) (*domain.Flat, error)
	GetFlatByID(id int64) (*domain.Flat, error)
	UpdateFlatStatus(flat *domain.Flat) (*domain.Flat, error)
	UpdateHouseLastAdded(houseID int64) error
	GetFlatsByHouseID(houseID int64, userType string) ([]domain.Flat, error)
	SubscribeToHouse(email string, houseID int64) error
	GetSubscribersByHouseID(houseID int64) ([]string, error)
}
