// Code generated by ifacemaker; DO NOT EDIT.

package realty

import (
	"realty/internal/domain"
)

// Controller describes methods, implemented by the usecase package.
type UseCase interface {
	CreateHouse(req *CreateHouseRequest) (*domain.House, error)
	GetHouseByID(HouseID int64) (*domain.House, error)
	CreateFlat(req *CreateFlatRequest) (*domain.Flat, error)
	GetFlatByID(flatID int64) (*domain.Flat, error)
	UpdateFlatStatus(req *UpdateFlatStatusRequest) (*domain.Flat, error)
	GetFlatsByHouseID(houseID int64, userType string) ([]domain.Flat, error)
	SubscribeToHouse(email string, houseID int64) error
	NotifySubscribers(houseID int64) error
}
