// Code generated by ifacemaker; DO NOT EDIT.

package auth

import (
	"github.com/gofiber/fiber/v3"
)

// Controller describes methods, implemented by the http package.
type Handlers interface {
	Register() fiber.Handler
	Login() fiber.Handler
}
