// Code generated by ifacemaker; DO NOT EDIT.

package auth

// Controller describes methods, implemented by the usecase package.
type UseCase interface {
	Register(req *RegisterRequest) (*RegisterResponse, error)
	Login(req *LoginRequest) (*LoginResponse, error)
}
